version: 2.1

commands:
  setup:
    description: 'Checkout project, cd into specified folder and install dependencies'
    parameters:
      path:
        type: string
        default: '~'
    steps:
      - checkout
      - restore_cache:
          key: << parameters.path >>-deps-{{ checksum "<< parameters.path >>/package.json"}}
      - run: |
          cd << parameters.path >>
          npm install
      - save_cache:
          key: << parameters.path >>-deps-{{ checksum "<< parameters.path>>/package.json" }}
          paths:
            - ~/<< parameters.path >>/node_modules

jobs:
  graphql:
    docker:
      - image: circleci/node:10.8.0
    steps:
      - setup:
          path: 'graphql'
      - run: |
          cd graphql
          npm run test-ci

  frontend:
    docker:
      - image: circleci/node:10.8.0
    steps:
      - setup:
          path: 'frontend'
      - run: |
          cd frontend
          npm run build

  frontend-deploy:
    docker:
      - image: circleci/node:10.8.0
    steps:
      - setup:
          path: 'frontend'
      - run: |
          cd frontend
          npm run build
          ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - graphql
      - frontend
      - request-deploy:
          type: approval
          requires:
            - graphql
            - frontend
          filters:
            branches:
              only:
                - master
      - frontend-deploy:
          requires:
            - request-deploy
